- name: catalogue
  hosts: catalogue
  become: yes 
  tasks:
    - name : Disable old NodeJS and Enable NodeJS 18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
      # Here we are using .shell in the ansible module because shell will work like it is logged inside the target machine and run.
      # .command will alwauys run from outside (Ansible Home Machine)

    - name: Install NodeJS
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Add roboshop user
      ansible.builtin.user:
        name : roboshop

    - name: Create App Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download Catalogue Application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/ 
    
    - name: Unzip the catalogue
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

