- name: shipping 
  hosts: shipping 
  become: yes 
  vars: 
    mysql_password: RoboShop@1
  tasks: 
    - name: Install maven 
      ansible.builtin.package:
        name: maven 
        state: present 

    - name: add roboshop user 
      ansible.builtin.user:
        name: roboshop 
    
    - name: recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent 

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download shipping.zip 
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp
    
    - name: unzipping shipping.zip 
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app 
        remote_src: yes  

    - name: Install dependicies
      ansible.builtin.command: mvn clean package 
      args:
        chdir: /app
      
    - name: Rename jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copy shipping.service 
      ansible.builtin.copy: 
        src: shipping.service 
        dest: /etc/systemd/system/shipping.service 

    - name: Daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true 

    - name: Enable and start shipping 
      ansible.builtin.service: 
        name: shipping 
        enabled: yes   
        state: restarted 

    - name: Install mysql client 
      ansible.builtin.dnf: 
        name: mysql 
        state: present

    - name: check cities schema exist or not
      ansible.builtin.command: mysql -h mysql.learndevops.space -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME= 'cities'"
      register: schema 

    - name: print output 
      ansible.builtin.debug:    
        msg: "schema output: {{schema}}" 

    - name: loading shipping data into mysql 
      ansible.builtin.shell: mysql -h mysql.learndevops.space -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
      when: schema.stdout == "0"

    - name: Restart shipping 
      ansible.builtin.service: 
        name: shipping  
        state: restarted 
